--1
SELECT STUDENT_NO, STUDENT_NAME, TO_CHAR(ENTRANCE_DATE, 'YYYY-MM-DD') FROM TB_STUDENT
ORDER BY ENTRANCE_DATE;
--2
SELECT PROFESSOR_NAME, PROFESSOR_SSN FROM TB_PROFESSOR
WHERE professor_name NOT LIKE '___';
--3
SELECT PROFESSOR_NAME, TRUNC(MONTHS_BETWEEN(SYSDATE, TO_NUMBER(SUBSTR(PROFESSOR_SSN, 1,6))/12))
FROM
TB_PROFESSOR;