SELECT * FROM TB_DEPARTMENT;
--1
SELECT DISTINCT DEPARTMENT_NAME  "학과 명",
CATEGORY "계열" FROM TB_DEPARTMENT;
--2
SELECT (DEPARTMENT_NAME||'의 정원은 '||CAPACITY||'명 입니다.') FROM TB_DEPARTMENT;
--3
SELECT STUDENT_NAME FROM TB_STUDENT 
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE (SUBSTR(STUDENT_SSN,8,1) = '2') AND DEPARTMENT_NAME='국어국문학과';
--