INSERT INTO EMPLOYEE  -- 모든 칼럼에 INSERT하고 싶은 경우 칼럼 명 생략 가능
-- 단, 칼럼의 순서를 지켜서 VALUES값에 대입
VALUES(  --넣을 실제 값
	900, '장채현', '901123-1080503', 'jang_ch@kh.or.kr', 
	'01055569512', 'D1', 'J8','S3', 4300000, 0.2, '200', 
	SYSDATE, NULL, DEFAULT
);

--구조 만들기
CREATE TABLE EMP_DEPT_D1
	AS SELECT EMP_ID, EMP_NAME, DEPT_CODE, HIRE_DATE 
	FROM EMPLOYEE WHERE 1=0;
    
CREATE TABLE EMP_MANAGER
	AS SELECT EMP_ID, EMP_NAME, MANAGER_ID
	FROM EMPLOYEE
	WHERE 1 = 0;
    
INSERT ALL
INTO EMP_DEPT_D1 VALUES(EMP_ID, EMP_NAME, DEPT_CODE, HIRE_DATE)
INTO EMP_MANAGER VALUES(EMP_ID, EMP_NAME, MANAGER_ID)
SELECT EMP_ID, EMP_NAME, DEPT_CODE, HIRE_DATE, MANAGER_ID
FROM EMPLOYEE
WHERE DEPT_CODE = 'D1';


CREATE TABLE EMP_OLD
AS SELECT EMP_ID, EMP_NAME, HIRE_DATE, SALARY 
FROM EMPLOYEE WHERE 1=0;

CREATE TABLE EMP_NEW
AS SELECT EMP_ID, EMP_NAME, HIRE_DATE, SALARY 
FROM EMPLOYEE WHERE 1=0;

INSERT ALL
WHEN HIRE_DATE < '2000/01/01' THEN 
	INTO EMP_OLD VALUES (EMP_ID, EMP_NAME, HIRE_DATE, SALARY)
WHEN HIRE_DATE >= '2000/01/01' THEN
	INTO EMP_NEW VALUES(EMP_ID, EMP_NAME, HIRE_DATE, SALARY)
SELECT EMP_ID, EMP_NAME, HIRE_DATE, SALARY
	FROM EMPLOYEE;