-- 부모 테이블
CREATE TABLE USER_GRADE(
GRADE_CODE NUMBER PRIMARY KEY,
GRADE_NAME VARCHAR2(30) NOT NULL
);
-- 행 삽입
INSERT INTO USER_GRADE VALUES(10, '일반회원');
INSERT INTO USER_GRADE VALUES(20, '우수회원');
INSERT INTO USER_GRADE VALUES(30, '특별회원');

SELECT * FROM USER_GRADE;

---------- 자식 테이블(FOREIGN KEY) -----------------
-- 생성 방법 1
CREATE TABLE USER_FOREIGNKEY(
	USER_NO NUMBER PRIMARY KEY,
	USER_ID VARCHAR2(20) UNIQUE,
	USER_PWD VARCHAR2(30) NOT NULL,
	USER_NAME VARCHAR2(30),
	GRADE_CODE NUMBER,
	FOREIGN KEY (GRADE_CODE) REFERENCES USER_GRADE( GRADE_CODE)
);

-- 생성 방법 2
CREATE TABLE USER_FOREIGNKEY(
	USER_NO NUMBER PRIMARY KEY,
	USER_ID VARCHAR2(20) UNIQUE,
	USER_PWD VARCHAR2(30) NOT NULL,
	USER_NAME VARCHAR2(30),
	GRADE_CODE NUMBER REFERENCES USER_GRADE (GRADE_CODE)
);


INSERT INTO USER_FOREIGNKEY
VALUES(1, 'user01', 'pass01', '홍길동', 10);  --성공

INSERT INTO USER_FOREIGNKEY
VALUES(2, 'user02', 'pass02', '이순신', 20); --성공

INSERT INTO USER_FOREIGNKEY
VALUES(3, 'user03', 'pass03', '유관순', 30); --성공

INSERT INTO USER_FOREIGNKEY
VALUES(4, 'user04', 'pass04', '심사임당', NULL); --성공

SELECT * FROM USER_FOREIGNKEY;

DELETE FROM USER_GRADE WHERE GRADE_CODE = 10;
--명령의 13 행에서 시작하는 중 오류 발생 -
--DELETE FROM USER_GRADE WHERE GRADE_CODE = 10
--오류 보고 -
--ORA-02292: 무결성 제약조건(KH.SYS_C008338)이 위배되었습니다- 자식 레코드가 발견되었습니다

DROP TABLE USER_FOREIGNKEY;
CREATE TABLE USER_FOREIGNKEY(
USER_NO NUMBER PRIMARY KEY,
USER_ID VARCHAR2(20) UNIQUE,
USER_PWD VARCHAR2(30) NOT NULL,
USER_NAME VARCHAR2(30),
GRADE_CODE NUMBER REFERENCES USER_GRADE (GRADE_CODE) ON DELETE CASCADE
);

DELETE FROM USER_GRADE WHERE GRADE_CODE = 10;

CREATE TABLE USER_CHECK(
USER_NO NUMBER PRIMARY KEY,
GENDER VARCHAR2(10) CHECK (GENDER IN ('남', '여'))
);

INSERT INTO USER_CHECK VALUES(1, '남자');
--명령의 70 행에서 시작하는 중 오류 발생 -
--INSERT INTO USER_CHECK VALUES(1, '남자')
--오류 보고 -
--ORA-02290: 체크 제약조건(KH.SYS_C008343)이 위배되었습니다

INSERT INTO USER_CHECK VALUES(1, '남');
DROP TABLE EMPLOYEE_COPY;
CREATE TABLE EMPLOYEE_COPY AS 
    SELECT EMP_ID, EMP_NAME, SALARY, DEPT_TITLE, JOB_NAME
	FROM EMPLOYEE E
	LEFT JOIN DEPARTMENT D ON (E.DEPT_CODE = D.DEPT_ID)
	LEFT JOIN JOB USING(JOB_CODE);
    
    
INSERT INTO EMPLOYEE (EMP_ID, EMP_NAME, EMP_NO, EMAIL, PHONE, DEPT_CODE,
JOB_CODE, SAL_LEVEL, SALARY, BONUS, MANAGER_ID,
HIRE_DATE, ENT_DATE, ENT_YN)
VALUES(900, '장채현', '901123-1080503', 'jang_ch@kh.or.kr', '01055569512', 'D1', 'J8',
'S3', 4300000, 0.2, '200', SYSDATE, NULL, DEFAULT);
