CREATE TABLE DEPT_COPY 
AS SELECT * FROM DEPARTMENT;

UPDATE DEPT_COPY SET DEPT_TITLE= '전략기획팀' WHERE  DEPT_ID = 'D9';

CREATE TABLE EMP_COPY AS SELECT EMP_ID, EMP_NAME, DEPT_CODE, SALARY, BONUS FROM EMPLOYEE;

SELECT * FROM EMP_COPY WHERE EMP_NAME IN ('유재식', '방명수');

UPDATE EMP_COPY SET 
SALARY = (SELECT SALARY FROM EMP_COPY WHERE EMP_NAME ='유재식'), 
BONUS = (SELECT BONUS FROM EMP_COPY WHERE EMP_NAME ='유재식')
WHERE EMP_NAME = '방명수';

UPDATE EMP_COPY 
	SET (SALARY, BONUS) = (SELECT SALARY, BONUS
	FROM EMP_COPY WHERE EMP_NAME = '유재식')
	WHERE EMP_NAME = '방명수';
	
UPDATE EMP_COPY 
	SET BONUS = 0.3
	WHERE EMP_ID IN (SELECT EMP_ID FROM EMP_COPY 
			JOIN DEPARTMENT ON (DEPT_ID = DEPT_CODE)
			JOIN LOCATION ON (LOCATION_ID = LOCAL_CODE)
			WHERE LOCAL_NAME LIKE 'ASIA%');
            
SELECT * FROM EMP_COPY;

DELETE FROM EMPLOYEE WHERE EMP_NAME = '장채현';

DELETE FROM DEPARTMENT WHERE DEPT_ID='D1';

SELECT * FROM USER_CONSTRAINTS;

ALTER TABLE EMPLOYEE MODIFY DEPT_CODE NOT NULL;

ALTER TABLE EMPLOYEE 
ADD CONSTRAINT EMP_DEPT_FK
FOREIGN KEY(DEPT_CODE) REFERENCES DEPARTMENT(DEPT_ID);

DESC EMPLOYEE;

INSERT INTO department VALUES ('D1','행정부','L1');

DESC department;

DELETE FROM DEPARTMENT WHERE DEPT_ID = 'D1'; --실패

ALTER TABLE EMPLOYEE
	DISABLE CONSTRAINT EMP_DEPT_FK CASCADE;
    
DELETE FROM DEPARTMENT WHERE DEPT_ID = 'D1'; --성공

ROLLBACK;

SELECT * FROM department;

ALTER TABLE EMPLOYEE
	ENABLE CONSTRAINT EMP_DEPT_FK;
