SELECT DEPT_CODE 부서코드, SUM(SALARY), FLOOR(AVG(SALARY)) 평균, COUNT(*) 인원수 FROM 
EMPLOYEE GROUP BY DEPT_CODE order by dept_code;

SELECT DEPT_CODE, COUNt(BONUS) FROM EMPLOYEE GROUP BY DEPT_CODE ORDER BY DEPT_CODE;

SELECT DECODE(SUBSTR(EMP_NO, 8, 1), 1, '남', 2, '여') 성별, 
FLOOR(AVG(SALARY)) 평균, 
SUM(SALARY) 합계,
COUNT(*) 인원수
FROM EMPLOYEE GROUP BY DECODE(SUBSTR(EMP_NO, 8, 1), 1, '남', 2, '여');

SELECT DEPT_CODE, FLOOR(AVG(SALARY)) FROM EMPLOYEE
GROUP BY DEPT_CODE HAVING FLOOR(AVG(SALARY)) >= 3000000 ORDER BY 1;

SELECT DEPT_CODE, FLOOR(AVG(SALARY)) 
FROM EMPLOYEE
WHERE SALARY >= 3000000a
GROUP BY DEPT_CODE
ORDER BY 1;

SELECT JOB_CODE, SUM(SALARY) FROM EMPLOYEE
GROUP BY ROLLUP(JOB_CODE) ORDER BY 1;

SELECT JOB_CODE, SUM(SALARY)
FROM EMPLOYEE
GROUP BY CUBE(JOB_CODE)
ORDER BY 1;

SELECT DEPT_CODE, JOB_CODE, SUM(SALARY) FROM EMPLOYEE 
GROUP BY ROLLUP(DEPT_CODE, JOB_CODE) ORDER BY 1;

SELECT DEPT_CODE, JOB_CODE, SUM(SALARY) FROM EMPLOYEE
GROUP BY CUBE(DEPT_CODE, JOB_CODE) ORDER BY 1;

SELECT DEPT_CODE, JOB_CODE, SUM(SALARY)
FROM EMPLOYEE
GROUP BY ROLLUP(DEPT_CODE, JOB_CODE)
UNION
SELECT '', JOB_CODE, SUM(SALARY)
FROM EMPLOYEE
GROUP BY ROLLUP(JOB_CODE)
ORDER BY 1;

SELECT DEPT_CODE, JOB_CODE, SUM(SALARY),
CASE 
WHEN 
GROUPING(DEPT_CODE) = 0 AND GROUPING(JOB_CODE) = 1  -- DEPT_CODE기준 전체 합
THEN '부서별 합계'

WHEN 
GROUPING(DEPT_CODE) = 1 AND GROUPING(JOB_CODE) = 0 -- JOB_CODE기준 전체 합
THEN '직급별 합계'

WHEN 
GROUPING(DEPT_CODE) = 1 AND GROUPING(JOB_CODE) = 1 -- 모두 합
THEN '총 합계'

ELSE '그룹별 합계'

END AS 구분

FROM EMPLOYEE
GROUP BY CUBE(DEPT_CODE, JOB_CODE)
ORDER BY 1;

SELECT EMP_ID, EMP_NAME, DEPT_CODE, SALARY
FROM EMPLOYEE
WHERE DEPT_CODE = 'D5'
UNION  -- OR 연산과 같음
SELECT EMP_ID, EMP_NAME, DEPT_CODE, SALARY
FROM EMPLOYEE
WHERE SALARY > 3000000;

SELECT EMP_ID, EMP_NAME, DEPT_CODE, SALARY
FROM EMPLOYEE
WHERE DEPT_CODE = 'D5' OR SALARY > 3000000;

SELECT EMP_ID, EMP_NAME, DEPT_CODE, SALARY
FROM EMPLOYEE
WHERE DEPT_CODE = 'D5'
INTERSECT
SELECT EMP_ID, EMP_NAME, DEPT_CODE, SALARY
FROM EMPLOYEE
WHERE SALARY > 3000000;

SELECT EMP_ID, EMP_NAME, DEPT_CODE, SALARY
FROM EMPLOYEE
WHERE DEPT_CODE = 'D5' AND SALARY > 3000000;

SELECT DEPT_CODE, JOB_CODE, MANAGER_ID, FLOOR(AVG(SALARY)) 
FROM EMPLOYEE
GROUP BY GROUPING SETS(
(DEPT_CODE, JOB_CODE, MANAGER_ID), 
(DEPT_CODE, MANAGER_ID),
(JOB_CODE, MANAGER_ID));

SELECT EMP_NAME, JOB_CODE, DEPT_CODE, SALARY, (SELECT FLOOR(AVG(SALARY)) FROM EMPLOYEE) AVGSAL FROM EMPLOYEE
WHERE SALARY >= (SELECT FLOOR(AVG(SALARY)) FROM EMPLOYEE) ORDER BY 2;

SELECT EMP_NAME, JOB_CODE, DEPT_CODE, SALARY FROM EMPLOYEE
WHERE SALARY IN (SELECT MAX(SALARY) FROM EMPLOYEE GROUP BY DEPT_CODE) ORDER BY 3;

SELECT EMP_NAME, JOB_CODE, DEPT_CODE, HIRE_DATE FROM EMPLOYEE
WHERE (DEPT_CODE, JOB_CODE) IN 
(SELECT DEPT_CODE, JOB_CODE FROM EMPLOYEE 
WHERE SUBSTR(EMP_NO, 8, 1) = 2 AND ENT_YN='Y');

SELECT ROWNUM, EMP_NAME, SALARY
FROM EMPLOYEE
WHERE ROWNUM <= 5
ORDER BY SALARY DESC;

WITH TOPN_SAL AS (SELECT EMP_NAME, SALARY FROM EMPLOYEE ORDER BY SALARY DESC)
SELECT ROWNUM, EMP_NAME, SALARY FROM TOPN_SAL;

SELECT 순위, EMP_NAME, SALARY
FROM (
SELECT EMP_NAME, SALARY, RANK() OVER(ORDER BY SALARY DESC) AS 순위
FROM EMPLOYEE
ORDER BY SALARY DESC
);

SELECT EMP_NAME, SALARY, RANK() OVER(ORDER BY SALARY DESC) AS 순위
FROM EMPLOYEE;