DROP SEQUENCE "SEQ_BOARD_ID";
CREATE SEQUENCE "SEQ_BOARD_ID";

DROP TABLE "BOARD_FILE";
DROP TABLE "BOARD_REPORT";
DROP TABLE "BOARD_REPLY";
DROP TABLE "LOGIN_LOG";

DROP TABLE "BOARD";
DROP TABLE "MEMBER";

CREATE TABLE "BOARD" (
	"BOARD_ID"	NUMBER		NOT NULL,
	"SUBJECT"	VARCHAR2(120)		NOT NULL,
	"CONTENT"	VARCHAR2(4000)		NOT NULL,
	"WRITE_TIME"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL,
	"LOG_IP"	VARCHAR2(15)		NULL,
	"BOARD_WRITER"	VARCHAR2(20)		NOT NULL,
	"READ_COUNT"	NUMBER	DEFAULT 0	NOT NULL
);

COMMENT ON COLUMN "BOARD"."BOARD_ID" IS '글 번호 SEQ_BOARD_ID';

COMMENT ON COLUMN "BOARD"."SUBJECT" IS '글제목 한글 40자, 영문 120자';

COMMENT ON COLUMN "BOARD"."CONTENT" IS '글 내용';

COMMENT ON COLUMN "BOARD"."WRITE_TIME" IS '글 작성 시간(2024-04-02 15:24)';

COMMENT ON COLUMN "BOARD"."LOG_IP" IS '글 작성시 단말의 IPV4';

COMMENT ON COLUMN "BOARD"."BOARD_WRITER" IS 'ON DELETE SET NULL';

COMMENT ON COLUMN "BOARD"."READ_COUNT" IS '글 읽기시 1씩 증가';



CREATE TABLE "MEMBER" (
	"MEM_ID"	VARCHAR(20)		NOT NULL,
	"MEM_PWD"	VARCHAR(20)		NOT NULL,
	"MEM_EMAIL"	VARCHAR2(100)		NOT NULL
);

COMMENT ON COLUMN "MEMBER"."MEM_ID" IS '멤버 아이디';

COMMENT ON COLUMN "MEMBER"."MEM_PWD" IS '멤버 비밀번호';

COMMENT ON COLUMN "MEMBER"."MEM_EMAIL" IS '멤버 이메일, 비번 재 설정시';



CREATE TABLE "BOARD_FILE" (
	"BOARD_FILE_ID"	NUMBER(5)	DEFAULT 1	NOT NULL,
	"BOARD_ID"	NUMBER		NOT NULL,
	"FILE_PATH"	VARCHAR2(1000)		NOT NULL,
	"ORIGINAL_FILENAME"	VARCHAR2(200)		NOT NULL
);

COMMENT ON COLUMN "BOARD_FILE"."BOARD_FILE_ID" IS 'BOARD_ID마다 임의의 숫자 식별자';

COMMENT ON COLUMN "BOARD_FILE"."BOARD_ID" IS '글 번호 SEQ_BOARD_ID';

COMMENT ON COLUMN "BOARD_FILE"."FILE_PATH" IS '저장된 파일 경로 파일명';

COMMENT ON COLUMN "BOARD_FILE"."ORIGINAL_FILENAME" IS '클라이언트 전송한 파일 명';



CREATE TABLE "LOGIN_LOG" (
	"LOG_TIME"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL,
	"LOG_IP"	VARCHAR2(15)		NULL,
	"MEM_ID"	VARCHAR(20)		NOT NULL,
	"LOG_TYPE"	CHAR(1)	DEFAULT 1	NOT NULL
);

COMMENT ON COLUMN "LOGIN_LOG"."LOG_TIME" IS '로그인아웃시간';

COMMENT ON COLUMN "LOGIN_LOG"."LOG_IP" IS '로그인 한 단말의 IPV4';

COMMENT ON COLUMN "LOGIN_LOG"."MEM_ID" IS '멤버 아이디';

COMMENT ON COLUMN "LOGIN_LOG"."LOG_TYPE" IS '로그인(1), 로그아웃(0)';



CREATE TABLE "BOARD_REPORT" (
	"MEM_ID"	VARCHAR(20)		NOT NULL,
	"BOARD_ID"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "BOARD_REPORT"."MEM_ID" IS '멤버 아이디';

COMMENT ON COLUMN "BOARD_REPORT"."BOARD_ID" IS '글 번호 SEQ_BOARD_ID';



CREATE TABLE "BOARD_REPLY" (
	"BOARD_REPLY_ID"	NUMBER		NOT NULL,
	"BOARD_ID"	NUMBER		NOT NULL,
	"BOARD_REPLY_WRITER"	VARCHAR2(20)		NOT NULL,
	"BOARD_REPLY_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"BOARD_REPLY_WRITE_TIME"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL,
	"BOARD_REPLY_LOG_IP"	VARCHAR2(15)		NULL,
	"BOARD_REPLY_LEVEL"	NUMBER(2)	DEFAULT 1	NOT NULL,
	"BOARD_REPLY_REF"	NUMBER		NULL,
	"BOARD_REPLY_STEP"	NUMBER(3)	DEFAULT 1	NOT NULL
);

COMMENT ON COLUMN "BOARD_REPLY"."BOARD_REPLY_ID" IS '댓글-1단계';

COMMENT ON COLUMN "BOARD_REPLY"."BOARD_ID" IS '글 번호 SEQ_BOARD_ID';

COMMENT ON COLUMN "BOARD_REPLY"."BOARD_REPLY_WRITER" IS '멤버 아이디';

COMMENT ON COLUMN "BOARD_REPLY"."BOARD_REPLY_CONTENT" IS '댓글 내용';

COMMENT ON COLUMN "BOARD_REPLY"."BOARD_REPLY_WRITE_TIME" IS '댓글 작성시간';

COMMENT ON COLUMN "BOARD_REPLY"."BOARD_REPLY_LOG_IP" IS '글작성시 단말의 IPV4';

COMMENT ON COLUMN "BOARD_REPLY"."BOARD_REPLY_LEVEL" IS '댓글1, 대댓글2, 대대댓글3';

COMMENT ON COLUMN "BOARD_REPLY"."BOARD_REPLY_REF" IS '최초 댓글의 번호 BOARD_REPLY_ID';

COMMENT ON COLUMN "BOARD_REPLY"."BOARD_REPLY_STEP" IS '최초 댓글 기준으로 몇번째인지';



ALTER TABLE "BOARD" ADD CONSTRAINT "PK_BOARD" PRIMARY KEY (
	"BOARD_ID"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MEM_ID"
);

ALTER TABLE "BOARD_FILE" ADD CONSTRAINT "PK_BOARD_FILE" PRIMARY KEY (
	"BOARD_FILE_ID",
	"BOARD_ID"
);

ALTER TABLE "LOGIN_LOG" ADD CONSTRAINT "PK_LOGIN_LOG" PRIMARY KEY (
	"LOG_TIME",
	"LOG_IP",
	"MEM_ID"
);

ALTER TABLE "BOARD_REPORT" ADD CONSTRAINT "PK_BOARD_REPORT" PRIMARY KEY (
	"MEM_ID",
	"BOARD_ID"
);

ALTER TABLE "BOARD_REPLY" ADD CONSTRAINT "PK_BOARD_REPLY" PRIMARY KEY (
	"BOARD_REPLY_ID"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_MEMBER_TO_BOARD_1" FOREIGN KEY (
	"BOARD_WRITER"
)
REFERENCES "MEMBER" (
	"MEM_ID"
);

ALTER TABLE "BOARD_FILE" ADD CONSTRAINT "FK_BOARD_TO_BOARD_FILE_1" FOREIGN KEY (
	"BOARD_ID"
)
REFERENCES "BOARD" (
	"BOARD_ID"
);

ALTER TABLE "LOGIN_LOG" ADD CONSTRAINT "FK_MEMBER_TO_LOGIN_LOG_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "MEMBER" (
	"MEM_ID"
);

ALTER TABLE "BOARD_REPORT" ADD CONSTRAINT "FK_MEMBER_TO_BOARD_REPORT_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "MEMBER" (
	"MEM_ID"
);

ALTER TABLE "BOARD_REPORT" ADD CONSTRAINT "FK_BOARD_TO_BOARD_REPORT_1" FOREIGN KEY (
	"BOARD_ID"
)
REFERENCES "BOARD" (
	"BOARD_ID"
);

ALTER TABLE "BOARD_REPLY" ADD CONSTRAINT "FK_BOARD_TO_BOARD_REPLY_1" FOREIGN KEY (
	"BOARD_ID"
)
REFERENCES "BOARD" (
	"BOARD_ID"
);

ALTER TABLE "BOARD_REPLY" ADD CONSTRAINT "FK_MEMBER_TO_BOARD_REPLY_1" FOREIGN KEY (
	"BOARD_REPLY_WRITER"
)
REFERENCES "MEMBER" (
	"MEM_ID"
);

