-------SEMIM DML-----------
set define off; -- & 대체 입력창이 아니라 문자 그대로 동작하게 함


--DROP TABLE "LOGIN_LOG";
--DROP TABLE "BOARD_FILE";
--DROP TABLE "BOARD_REPORT";
--DROP TABLE "BOARD_REPLY";
--    DROP TABLE "BOARD";
--        DROP TABLE "MEMBER";

--insert 순서는 drop의 반대로
------TABLE MEMBER insert
DESC MEMBER;
--MEM_ID    NOT NULL VARCHAR2(20)  
--MEM_PWD   NOT NULL VARCHAR2(20)  
--MEM_EMAIL NOT NULL VARCHAR2(100) 

INSERT INTO MEMBER VALUES('kh1','pwd1','kh1@a.com');
INSERT INTO MEMBER VALUES('kh2','pwd2','kh2@a.com');
INSERT INTO MEMBER VALUES('kh3','pwd3','kh3@a.com');
INSERT INTO MEMBER VALUES('kh4','pwd4','kh4@a.com');
INSERT INTO MEMBER VALUES('kh5','pwd5','kh5@a.com');
--SELECT * FROM MEMBER;
COMMIT;

------TABLE BOARD insert
DESC BOARD;
--BOARD_ID     NOT NULL NUMBER         
--SUBJECT      NOT NULL VARCHAR2(120)  
--CONTENT      NOT NULL VARCHAR2(4000) 
--WRITE_TIME   NOT NULL TIMESTAMP(6)   
--LOG_IP                VARCHAR2(15)   
--BOARD_WRITER NOT NULL VARCHAR2(20)   
--READ_COUNT   NOT NULL NUMBER    
INSERT INTO BOARD VALUES(SEQ_BOARD_ID.NEXTVAL,'제목1','내용1',DEFAULT,'127.0.0.1','kh1',DEFAULT);
INSERT INTO BOARD VALUES(SEQ_BOARD_ID.NEXTVAL,'제목2','내용2',DEFAULT,'127.0.0.1','kh2',DEFAULT);
INSERT INTO BOARD VALUES(SEQ_BOARD_ID.NEXTVAL,'제목3','내용3',DEFAULT,'127.0.0.1','kh3',DEFAULT);
INSERT INTO BOARD VALUES(SEQ_BOARD_ID.NEXTVAL,'제목4','내용4',DEFAULT,'127.0.0.1','kh4',DEFAULT);
INSERT INTO BOARD VALUES(SEQ_BOARD_ID.NEXTVAL,'제목5','내용5',DEFAULT,'127.0.0.1','kh5',DEFAULT);
SELECT * FROM board ORDER BY WRITE_TIME DESC;
COMMIT;

------TABLE BOARD_REPLY insert
DESC BOARD_REPLY;
--BOARD_REPLY_ID         NOT NULL NUMBER         
--BOARD_ID               NOT NULL NUMBER         
--BOARD_REPLY_WRITER     NOT NULL VARCHAR2(20)   
--BOARD_REPLY_CONTENT    NOT NULL VARCHAR2(4000) 
--BOARD_REPLY_WRITE_TIME NOT NULL TIMESTAMP(6)   
--BOARD_REPLY_LOG_IP              VARCHAR2(15)   
--BOARD_REPLY_LEVEL      NOT NULL NUMBER(2)      
--BOARD_REPLY_REF        NOT NULL NUMBER         
--BOARD_REPLY_STEP       NOT NULL NUMBER(3)  

select * from BOARD_REPLY;
--BOARD_1D : 5댓글들 ..달기
-- 댓글 -원본글
INSERT INTO BOARD_REPLY VALUES( (SELECT NVL(MAX(BOARD_REPLY_ID),0)+1 FROM BOARD_REPLY), 5,
    'kh1', '원래댓글', default, null, 
    1, (SELECT NVL(MAX(BOARD_REPLY_ID),0)+1 FROM BOARD_REPLY), 1 );
--대댓글(1번 글에)  ( BOARD_REPLY_STEP 이 중요함 )
INSERT INTO BOARD_REPLY VALUES( (SELECT NVL(MAX(BOARD_REPLY_ID),0)+1 FROM BOARD_REPLY), 5,
    'kh1', '대댓글1', default, null, 
    2, 1, 2 );
    
--추가 대댓글(1번 글에) + 다른 댓글 BOARD_REPLY_STEP uodate가 같이 들어가야됨
--INSERT INTO BOARD_REPLY VALUES( (SELECT NVL(MAX(BOARD_REPLY_ID),0)+1 FROM BOARD_REPLY), 5,
--    'kh1', '대댓글2', default, null, 
--    2, 1, 2 );


--대대댓글(1번글에)
INSERT INTO BOARD_REPLY VALUES( (SELECT NVL(MAX(BOARD_REPLY_ID),0)+1 FROM BOARD_REPLY), 5,
    'kh1', '대대댓글1', default, null, 
    3, 1, 3 );
    
-- 댓글 -원본글
INSERT INTO BOARD_REPLY VALUES( (SELECT NVL(MAX(BOARD_REPLY_ID),0)+1 FROM BOARD_REPLY), 5,
    'kh1', '댓글2', default, null, 
    1, (SELECT NVL(MAX(BOARD_REPLY_ID),0)+1 FROM BOARD_REPLY), 1 );
-- 댓글 -원본글   
INSERT INTO BOARD_REPLY VALUES( (SELECT NVL(MAX(BOARD_REPLY_ID),0)+1 FROM BOARD_REPLY), 5,
    'kh1', '댓글3', default, null, 
    1, (SELECT NVL(MAX(BOARD_REPLY_ID),0)+1 FROM BOARD_REPLY), 1 );
    
    
--추가 대댓글(1번 글에) + 다른 댓글 BOARD_REPLY_STEP uodate가 같이 들어가야됨
UPDATE BOARD_REPLY SET BOARD_REPLY_STEP = BOARD_REPLY_STEP + 1 
    WHERE BOARD_REPLY_STEP > 1;  --1보다 큰 애들 밀어내고 대댓글 2 넣음

INSERT INTO BOARD_REPLY VALUES( (SELECT NVL(MAX(BOARD_REPLY_ID),0)+1 FROM BOARD_REPLY), 5,
    'kh1', '대댓글2', default, null, 
    2, 1, 2 );
    
--추가 대대댓글(대댓글2번글에)
UPDATE BOARD_REPLY SET BOARD_REPLY_STEP = BOARD_REPLY_STEP + 1 
    WHERE BOARD_REPLY_STEP >  (SELECT BOARD_REPLY_STEP FROM BOARD_REPLY WHERE BOARD_REPLY_ID = 6);
--2;  
INSERT INTO BOARD_REPLY VALUES( (SELECT NVL(MAX(BOARD_REPLY_ID),0)+1 FROM BOARD_REPLY), 5,
    'kh1', '대대댓글2', default, null, 
    3, 1, 3 );   
    
    
--대댓글 (5번글에)
UPDATE BOARD_REPLY SET BOARD_REPLY_STEP = BOARD_REPLY_STEP + 1 
    WHERE
    BOARD_REPLY_REF = (SELECT BOARD_REF FROM BOARD_REPLY WHERE BOARD_REPLY_ID=1)
    AND
    BOARD_REPLY_STEP > (SELECT BOARD_REPLY_STEP FROM BOARD_REPLY WHERE BOARD_REPLY_ID = 5);
        
INSERT INTO BOARD_REPLY VALUES( 
    (SELECT NVL(MAX(BOARD_REPLY_ID),0)+1 FROM BOARD_REPLY), 5,
    'kh1', '5번대댓글1', default, null, 
    (SELECT BOARD_REPLY_LEVEL +1 FROM BOARD_REPLY WHERE BOARD_REPLY_ID = 5), 
    (SELECT BOARD_REPLY_REF FROM BOARD_REPLY WHERE BOARD_REPLY_ID = 5), 
    (SELECT BOARD_REPLY_STEP +1 FROM BOARD_REPLY WHERE BOARD_REPLY_ID = 5) 
);   

--대댓글 (번글에)
UPDATE BOARD_REPLY SET BOARD_REPLY_STEP = BOARD_REPLY_STEP + 1 WHERE
    BOARD_REPLY_REF = (SELECT BOARD_REPLY_REF FROM BOARD_REPLY WHERE BOARD_REPLY_ID=3)
    AND
    BOARD_REPLY_STEP > (SELECT BOARD_REPLY_STEP FROM BOARD_REPLY WHERE BOARD_REPLY_ID = 3);
        
INSERT INTO BOARD_REPLY VALUES( 
    (SELECT NVL(MAX(BOARD_REPLY_ID),0)+1 FROM BOARD_REPLY), 5,
    'kh1', '3번대댓글1', default, null, 
    (SELECT BOARD_REPLY_LEVEL +1 FROM BOARD_REPLY WHERE BOARD_REPLY_ID = 3), 
    (SELECT BOARD_REPLY_REF FROM BOARD_REPLY WHERE BOARD_REPLY_ID = 3), 
    (SELECT BOARD_REPLY_STEP +1 FROM BOARD_REPLY WHERE BOARD_REPLY_ID = 3) 
);   
    
    
select * from BOARD_REPLY
order by board_reply_ref desc, board_reply_step asc; 

DELETE FROM BOARD_REPLY;