REVOKE CREATE SESSION from kh;

grant connect, resource to kh, kh2;

grant connect, resource, UNLIMITED TABLESPACE to kh, kh2;

select * from employee;
select * from department;
select * from job;

select emp_id, emp_name, job_code, hire_date from employee;

SELECT EMP_NAME, SALARY*12, (SALARY + (SALARY*BONUS)) *12 AbCDe FROM EMPLOYEE;

SELECT EMP_NAME AS 이름, SALARY*12 "연봉(원)", (SALARY+(SALARY*BONUS))*12 "총소득(원)" FROM EMPLOYEE;

SELECT EMP_ID,SALARY, '원' AS 단위, '100a' as ab FROM EMPLOYEE;

SELECT DISTINCT JOB_CODE FROM EMPLOYEE;

SELECT EMP_NAME, DEPT_CODE FROM EMPLOYEE WHERE DEPT_CODE <> 'D9';

SELECT EMP_NAME, SALARY FROM EMPLOYEE WHERE SALARY > 4000000;

SELECT EMP_NAME, DEPT_CODE, SALARY FROM EMPLOYEE WHERE DEPT_CODE='D6' AND SALARY > 2000000;

SELECT EMP_ID || EMP_NAME || SALARY 
FROM EMPLOYEE;

SELECT EMP_NAME || '의 월급은 ' || SALARY || '원 입니다.' 
FROM EMPLOYEE;

SELECT EMP_NAME, SALARY || '원' AS EX1 FROM EMPLOYEE;

SELECT EMP_NAME, SALARY FROM EMPLOYEE
WHERE SALARY >= 3500000 AND SALARY <= 6000000;

SELECT EMP_NAME, SALARY FROM EMPLOYEE WHERE EMP_NAME LIKE '전%';

SELECT EMP_NAME, PHONE FROM EMPLOYEE WHERE PHONE LIKE '___7%';

SELECT EMP_NAME, EMAIL FROM EMPLOYEE WHERE EMAIL LIKE '___$_%' ESCAPE '$';

SELECT EMP_ID, EMP_NAME, EMAIL FROM EMPLOYEE WHERE EMP_NAME NOT LIKE '이%';

SELECT EMP_ID, EMP_NAME, EMAIL FROM EMPLOYEE WHERE NOT EMP_NAME LIKE '이%';

SELECT EMP_NAME, MANAGER_ID, DEPT_CODE FROM EMPLOYEE 
WHERE  MANAGER_ID IS NULL AND DEPT_CODE IS NULL;

SELECT EMP_NAME, BONUS, DEPT_CODE FROM EMPLOYEE
WHERE DEPT_CODE IS NULL AND BONUS IS NOT NULL;

SELECT EMP_NAME, DEPT_CODE, SALARY FROM EMPLOYEE
WHERE DEPT_CODE IN ('D9','D8');

SELECT EMP_NAME, DEPT_CODE, SALARY FROM EMPLOYEE
WHERE DEPT_CODE = 'D9' OR DEPT_CODE = 'D8';

SELECT EMP_NAME, SALARY, JOB_CODE FROM EMPLOYEE 
WHERE JOB_CODE IN ('J2', 'J7') AND SALARY > 2000000;

SELECT EMP_NAME, SALARY, JOB_CODE
FROM EMPLOYEE
WHERE JOB_CODE = 'J7' OR JOB_CODE = 'J2'
AND SALARY > 2000000;

SELECT EMP_NAME, SALARY, JOB_CODE
FROM EMPLOYEE
WHERE (JOB_CODE = 'J7' OR JOB_CODE = 'J2')
AND SALARY > 2000000;

SELECT EMP_NAME, LENGTH(EMP_NAME), EMAIL, LENGTH(EMAIL) FROM EMPLOYEE;

SELECT EMP_NAME, LENGTHB(EMP_NAME), EMAIL, LENGTHB(EMAIL) FROM EMPLOYEE;

SELECT EMAIL, INSTR(EMAIL, '@', -1,1) 위치 FROM EMPLOYEE;

SELECT RPAD(EMAIL, 20, '#') FROM EMPLOYEE;

SELECT EMP_NAME, LTRIM(PHONE, '010'), RTRIM(EMAIL ,'@KH.or.kr') FROM EMPLOYEE;

SELECT LTRIM(' KH') FROM DUAL;

SELECT SUBSTR('SHOWMETHEMONEY', 5, 2) FROM DUAL;

SELECT INITCAP('Welcome To My World') FROM DUAL;

SELECT CONCAT('가나다라', 'ABC') FROM DUAL;

SELECT INSTRB('가나다라마바','나',4) FROM DUAL;

SELECT INSTRB('ABCDEFG','D',4) FROM DUAL;

SELECT TO_DATE( '2024/03/24', 'yyyy/mm/dd') c1 
, sysdate c2
, months_between(to_date('2024/03/26', 'yyyy/mm/dd'), sysdate) c3 
from dual;

select to_char(SYSDATE, 'yyyy/mm/dd hh24:mi:ss') from dual;

--깃 연동완료