--1
SELECT EMP_NAME, EMP_NO, DEPT_TITLE, JOB_NAME FROM EMPLOYEE
JOIN DEPARTMENT ON DEPT_CODE = DEPT_ID
JOIN JOB USING (JOB_CODE)
WHERE TO_NUMBER(SUBSTR(EMP_NO, 0,2)) BETWEEN 77 AND 79 AND 
TO_NUMBER(SUBSTR(EMP_NO, 8,1)) = 2;
--2
SELECT EMP_ID, EMP_NAME, EXTRACT(YEAR FROM SYSDATE) - (1900 + TO_NUMBER(SUBSTR(EMP_NO, 0,2))) "나이",
DEPT_TITLE, JOB_NAME FROM EMPLOYEE
JOIN DEPARTMENT ON DEPT_CODE = DEPT_ID
JOIN JOB USING (JOB_CODE)
WHERE TO_NUMBER(SUBSTR(EMP_NO, 0,2)) = (SELECT MAX(TO_NUMBER(SUBSTR(EMP_NO, 0,2))) FROM EMPLOYEE);
--3
SELECT EMP_ID, EMP_NAME, JOB_CODE FROM EMPLOYEE
WHERE EMP_NAME LIKE '%형%';
--4





