SELECT * FROM EMP WHERE COMM IS NOT NULL;

SELECT * FROM EMP WHERE COMM IS NULL OR COMM = 0;

SELECT * FROM EMP WHERE MGR IS NULL;

SELECT * FROM EMP ORDER BY SAL DESC;

SELECT * FROM EMP ORDER BY SAL DESC, COMM;

SELECT EMPNO, ENAME, JOB, HIREDATE FROM EMP ORDER BY HIREDATE;

SELECT EMPNO, ENAME FROM EMP ORDER BY EMPNO DESC;

SELECT EMPNO, HIREDATE, ENAME, SAL FROM EMP ORDER BY DEPTNO, HIREDATE DESC;

SELECT SYSDATE FROM DUAL;

SELECT EMPNO, ENAME, TRUNC(SAL, -2) FROM EMP;

SELECT * FROM EMP WHERE(MOD(EMPNO, 2) != 0);

SELECT ENAME, EXTRACT(YEAR FROM HIREDATE), EXTRACT(MONTH FROM HIREDATE) FROM EMP;

SELECT * FROM EMP WHERE EXTRACT(MONTH FROM HIREDATE) = '9';

SELECT * FROM EMP WHERE SUBSTR(EXTRACT(YEAR FROM HIREDATE),3,2) = '81';

SELECT * FROM EMP WHERE ENAME LIKE '%E';

SELECT * FROM EMP WHERE SUBSTR(ENAME, -1,1) = 'E';

SELECT EMPNO, ENAME, HIREDATE, HIREDATE + (INTERVAL '40' YEAR) AS "40년" FROM EMP;

SELECT * FROM EMP WHERE hiredate <= SYSDATE + (INTERVAL '-38' YEAR);

SELECT EXTRACT(YEAR FROM SYSDATE) FROM DUAL;