--1
SELECT EMP_NAME, EMP_NO, DEPT_TITLE, JOB_NAME FROM EMPLOYEE
JOIN DEPARTMENT ON DEPT_CODE = DEPT_ID
JOIN JOB USING (JOB_CODE)
WHERE TO_NUMBER(SUBSTR(EMP_NO, 0,2)) BETWEEN 70 AND 79 AND 
TO_NUMBER(SUBSTR(EMP_NO, 8,1)) = 2;
--2
SELECT EMP_ID, EMP_NAME, EXTRACT(YEAR FROM SYSDATE) - (1900 + TO_NUMBER(SUBSTR(EMP_NO, 0,2))) "나이",
DEPT_TITLE, JOB_NAME FROM EMPLOYEE
JOIN DEPARTMENT ON DEPT_CODE = DEPT_ID
JOIN JOB USING (JOB_CODE)
WHERE TO_NUMBER(SUBSTR(EMP_NO, 0,2)) = (SELECT MAX(TO_NUMBER(SUBSTR(EMP_NO, 0,2))) FROM EMPLOYEE);
--3
SELECT EMP_ID, EMP_NAME, JOB_CODE FROM EMPLOYEE
WHERE EMP_NAME LIKE '%형%';
--4
SELECT EMP_NAME, JOB_NAME, DEPT_CODE, DEPT_TITLE FROM EMPLOYEE
JOIN department ON DEPT_CODE = DEPT_ID
JOIN JOB USING (JOB_CODE)
WHERE DEPT_CODE IN('D5', 'D6');
--5
SELECT EMP_NAME, BONUS, DEPT_TITLE, LOCAL_NAME FROM EMPLOYEE
JOIN department ON DEPT_CODE = DEPT_ID
JOIN LOCATION ON LOCATION_ID = LOCAL_CODE 
WHERE BONUS IS NOT NULL;
--6
SELECT EMP_NAME, JOB_NAME, DEPT_TITLE, LOCAL_NAME
FROM EMPLOYEE
JOIN JOB USING (JOB_CODE)
JOIN department ON DEPT_CODE = DEPT_ID
JOIN LOCATION ON LOCATION_ID = LOCAL_CODE;
--7
SELECT EMP_NAME, DEPT_TITLE, LOCAL_NAME, NATIONAL_NAME
FROM EMPLOYEE
JOIN department ON DEPT_CODE = DEPT_ID
JOIN LOCATION ON LOCATION_ID = LOCAL_CODE
JOIN NATIONAL USING (NATIONAL_CODE)
WHERE NATIONAL_NAME IN ('한국', '일본');
--8

--9
SELECT EMP_NAME, JOB_NAME, NVL(SALARY,0) FROM EMPLOYEE
JOIN JOB USING (JOB_CODE)
WHERE JOB_CODE IN ('J4', 'J7');
--10
SELECT *
FROM (
    SELECT EMP_ID, EMP_NAME, DEPT_TITLE, JOB_NAME, HIRE_DATE, RANK() OVER(ORDER BY SALARY DESC) 순위
    FROM employee
    JOIN DEPARTMENT ON DEPT_CODE = DEPT_ID
    JOIN JOB USING (JOB_CODE)
)
WHERE 순위 <= 5;
--11

--12






